import Head from "next/head";
import { ImDownload3, ImLab } from "react-icons/im";
import { HiUserGroup } from "react-icons/hi";
import { AiOutlineSound } from "react-icons/ai";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mairala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <header className="w-full">
          <nav className="flex justify-between py-8 mx-auto items-center bg-[#303030] px-48">
            <div className="rounded-full text-white">
              <h3 className="font-os font-bold text-5xl">Mairala</h3>
            </div>
            <div className="space-x-12 flex text-white text-sm font-raleway uppercase">
              <a href="#" className="pb-2 border-b-4 border-brown">
                Home
              </a>
              <a href="#about">About</a>
              <a href="#portfolio">Portfolios</a>
              <a href="#team">Team</a>
              <a href="#blog">Blog</a>
              <a href="#contact">Contact</a>
            </div>
          </nav>
        </header>

        <section className="bg-primary-dark w-full px-48 py-[180px] font-raleway">
          <div className="w-fit">
            <p className="uppercase align-left text-2xl mb-4 text-white">
              Grab your copy of
            </p>
            <h1 className="mb-4 text-[66px] text-white uppercase font-semibold leading-[1]">
              The <span className="text-brown">Premium</span> Quality
            </h1>
            <h1 className="mb-4 text-[66px] text-white uppercase font-semibold leading-[1]">
              PSD Template For <span className="text-brown">free</span>
            </h1>
          </div>
          <button className="uppercase bg-secondary-dark text-white px-10 py-2 rounded flex items-center">
            <span className="mr-2">Download</span> <ImDownload3 />
          </button>
        </section>

        <section
          className="mt-[80px] text-center px-48 font-raleway"
          id="about"
        >
          <h3 className="uppercase text-brown text-2xl font-semibold mb-8">
            Services we provide
          </h3>
          <p className="text-black text-base mb-[80px]">
            Volutpat wisi enim ad minim veniam, quis nostrud exerci tation
            ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo
            consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate
            velit esse molestie consequat, vel illum dolore eu feugiat nulla
            facilisis at vero eros et accumsan et iusto odio dignissim qui
            blandit praesent{" "}
          </p>
          <div className="flex justify-between">
            <div className="flex justify-center flex-col items-center">
              <span className="mb-4">
                <HiUserGroup className="text-3xl" />
              </span>
              <h3 className="uppercase text-[#363636] mb-4">Consultancy</h3>
              <p className="text-neutral text-base">
                Claritas est etiam processus dynaicus qui sequitur mutationem
                consuetudium lectorum. Mirum est notare quam{" "}
              </p>
            </div>
            <div className="flex justify-center flex-col items-center">
              <span className="mb-4">
                <AiOutlineSound className="text-3xl" />
              </span>
              <h3 className="uppercase text-[#363636] mb-4">Marketing</h3>
              <p className="text-neutral text-base">
                Claritas est etiam processus dynaicus qui sequitur mutationem
                consuetudium lectorum. Mirum est notare quam{" "}
              </p>
            </div>
            <div className="flex justify-center flex-col items-center">
              <span className="mb-4">
                <ImLab className="text-3xl" />
              </span>
              <h3 className="uppercase text-[#363636] mb-4">Research</h3>
              <p className="text-neutral text-base">
                Claritas est etiam processus dynaicus qui sequitur mutationem
                consuetudium lectorum. Mirum est notare quam{" "}
              </p>
            </div>
          </div>
        </section>
        <section id="blog" className="mt-[80px] text-center px-48 font-raleway">
          <h2 className="text-4xl font-semibold uppercase text-brown pb-[50px]">
            Our Blog
          </h2>
          <div className="border-b-8 border-brown mb-[50px] mx-auto w-[80px]" />
          <p className="text-center w-1/2 mx-auto text-[18px] text-[#212121]">
            Nam liber tempor cum soluta nobis eleifend option congue nihil
            imperdiet doming id quod mazim
          </p>
          <div>
            <div className="mt-[90px] grid grid-cols-2 gap-8">
              <div>
                <img
                  src="https://res.cloudinary.com/ds2ene5mm/image/upload/v1656241200/Screen_Shot_2022-06-26_at_6.59.27_PM_gl7at2.png"
                  alt="camera"
                  className="w-[470px]"
                />
              </div>
              <div className="text-left">
                <p className="text-brown text-base">10 April 2014</p>
                <h4 className="text-2xl text-[#212121] mb-8">
                  Typi non habent claritatem insitam
                </h4>
                <p className="text-base text-neutral">
                  Duis autem vel eum iriure dolor in hendrerit in vulputate
                  velit esse molestie consequat, vel illum dolore eu feugiat
                  nulla facilisis at vero eros et accumsan et iusto odio
                  dignissim qui
                </p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-8 mt-[50px]">
              <div className="text-right">
                <p className="text-brown text-base">10 April 2014</p>
                <h4 className="text-2xl text-[#212121] mb-8">
                  Typi non habent claritatem insitam
                </h4>
                <p className="text-base text-neutral">
                  Duis autem vel eum iriure dolor in hendrerit in vulputate
                  velit esse molestie consequat, vel illum dolore eu feugiat
                  nulla facilisis at vero eros et accumsan et iusto odio
                  dignissim qui
                </p>
              </div>
              <div>
                <img
                  src="https://res.cloudinary.com/ds2ene5mm/image/upload/v1656241200/Screen_Shot_2022-06-26_at_6.59.27_PM_gl7at2.png"
                  alt="camera"
                  className="w-[470px]"
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-8 mt-[50px]">
              <div>
                <img
                  src="https://res.cloudinary.com/ds2ene5mm/image/upload/v1656241200/Screen_Shot_2022-06-26_at_6.59.27_PM_gl7at2.png"
                  alt="camera"
                  className="w-[470px] object-fill"
                />
              </div>
              <div className="text-left">
                <p className="text-brown text-base">10 April 2014</p>
                <h4 className="text-2xl text-[#212121] mb-8">
                  Typi non habent claritatem insitam
                </h4>
                <p className="text-base text-neutral">
                  Duis autem vel eum iriure dolor in hendrerit in vulputate
                  velit esse molestie consequat, vel illum dolore eu feugiat
                  nulla facilisis at vero eros et accumsan et iusto odio
                  dignissim qui
                </p>
              </div>
            </div>
          </div>
        </section>
        <section
          id="contact"
          className="mt-[80px] text-center px-48 font-raleway bg-[#f5f5f5]"
        >
          <h2 className="text-brown font-semibold text-5xl uppercase pt-[90px]">
            Contact
          </h2>
          <div className="mt-[50px] pb-[85px]">
            <form>
              <div className="grid grid-cols-2 gap-12 mb-2">
                <div className="flex flex-col text-left">
                  <input
                    type="text"
                    className="outline-none bg-transparent border-b-4 border-[#242424] mb-2"
                  />
                  <label className="ml-4 text-brown">Name*</label>
                </div>
                <div className="flex flex-col text-left">
                  <input
                    type="email"
                    className="outline-none bg-transparent border-b-4 border-[#242424] mb-2"
                  />
                  <label className="ml-4 text-brown">Email*</label>
                </div>
              </div>
              <div className="flex flex-col text-left">
                <textarea className="outline-none bg-transparent border-b-4 border-[#242424] mb-2" />
                <label className="ml-4 text-brown">Message...</label>
              </div>

              <div className="mt-[120px] mb-8 border-b border-[#242424]" />

              <button
                type="submit"
                className="border-2 border-[#242424] px-10 py-2"
              >
                Submit
              </button>
            </form>
          </div>
        </section>
        <section className="bg-[#222222] w-full px-48 pt-[54px] font-raleway text-white grid grid-cols-4 gap-8 pb-8">
          <div className="text-neutral text-sm">
            <h3 className="font-bold font-os text-5xl text-brown mb-6">
              Mairala
            </h3>
            <p className="mb-6">
              Duis autem vel eum iriure dolor in hendrerit in vulputate velit
              esse molestie consequat, vel illum dolore.
            </p>
            <p>
              eugiat nulla facilisis at vero eros et accumsan et iusto odio
              dignissim qui blandit praesent luptatum zzril delenit augue duis
              dolore te feugait nulla facilisi. Nam liber tempor cum soluta{" "}
            </p>
          </div>
          <div>
            <h3 className="text-[#c2c2c2] uppercase text-[18px] font-semibold mb-6">
              Recent Posts
            </h3>
            <div className="pb-8 mb-8 border-b border-[#5f5f5f]">
              <p className="text-[10px] text-[#5f5f5f]">March 30, 2014</p>
              <p className="text-sm text-neutral">
                Duis autem vel eum iriure dolor
              </p>
            </div>

            <div className="pb-8 mb-8 border-b border-[#5f5f5f]">
              <p className="text-[10px] text-[#5f5f5f]">March 30, 2014</p>
              <p className="text-sm text-neutral">
                Duis autem vel eum iriure dolor
              </p>
            </div>

            <div className="pb-8 mb-8 border-b border-[#5f5f5f]">
              <p className="text-[10px] text-[#5f5f5f]">March 30, 2014</p>
              <p className="text-sm text-neutral">
                Duis autem vel eum iriure dolor
              </p>
            </div>
          </div>
          <div>
            <h3 className="text-[#c2c2c2] uppercase text-[18px] font-semibold mb-6">
              Twitter Feeds
            </h3>
            <div className="pb-7 mb-8 border-b border-[#5f5f5f]">
              <p className="flex items-center">
                {" "}
                <span className="text-[10px] text-[#5f5f5f] mr-2">
                  March 30, 2014
                </span>
                <span className="text-brown text-sm">@kristianplatt</span>
              </p>
              <p className="text-sm text-neutral">Good work buddy</p>
            </div>
            <div className="pb-7 mb-8 border-b border-[#5f5f5f]">
              <p className="flex items-center">
                {" "}
                <span className="text-[10px] text-[#5f5f5f] mr-2">
                  March 30, 2014
                </span>
                <span className="text-brown text-sm">@fasteven</span>
              </p>
              <p className="text-sm text-neutral">Good work buddy</p>
            </div>
            <div className="pb-6 mb-8 border-b border-[#5f5f5f]">
              <p className="flex items-center">
                {" "}
                <span className="text-[10px] text-[#5f5f5f] mr-2">
                  March 30, 2014
                </span>
                <span className="text-brown text-sm">@streamer</span>
              </p>
              <p className="text-sm text-neutral">Good work buddy</p>
            </div>
          </div>
          <div>
            <h3 className="text-[#c2c2c2] uppercase text-[18px] font-semibold mb-6">
              Our Address
            </h3>
            <p className="text-sm text-neutral">
              Investigationes demonstraverunt lectores legere me lius quod ii
              legunt saepius. Claritas est etiam processus dynamicus,luptatum
              zzril delenit augue duis dolore te feugait nulla facilisi. Nam
              liber tempor cum soluta
            </p>
            <div className="mt-[50px] text-sm text-neutral">
              <p>Moonshine St. 14/05 Light, Jupiter</p>
              <p>+00 (123) 456 78 90</p>
              <p>first.last@email.com</p>
            </div>
          </div>
        </section>
        <footer className="w-full text-center bg-[#1c1c1c] py-6 text-[#595959] text-base">
          <p>©2014 Imran Khan All Rights Reserved</p>
        </footer>
      </main>
    </div>
  );
}
